# Tema 2 Numpy - Clase 1

## Importacion de librerias

In [9]:
import numpy as np

In [10]:
#creacion de arrays de una dimension con eje 0(horizontal(x))

a1 = np.array([1,2,3])
print(a1) 

[1 2 3]


In [11]:
#creacion de arrays de dos dimensiones(vertical(y) y horizontal(x))
#np.array([[y],[x]])

a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
#creacion de arrays de tres dimensiones

array3= np.array([[[1,2,3],[4,5,6],[7,8,9]]])
array3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
#uso de otras funciones para generar arrays

print(np.zeros((3,4)))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
# funcion que el primer valor es donde empieza la matriz, segundo, el final y tercero cuantas partes vamos a dividir

np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [15]:
# funcion que el primer numero me indica donde empieza el segundo es donde acaba menos 1 y el tercer es el numero de saltos

np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# matriz de indentidad donde n es la dimension de tu matriz

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# funcion que crea una matriz random con las dimensiones que desees

np.random.random((3,3))

array([[0.63010022, 0.79721988, 0.32785058],
       [0.81683992, 0.42742962, 0.97085479],
       [0.8387446 , 0.33981599, 0.57305675]])

In [18]:
# funcion que crea una matriz en el que el primer valor indica las dimensiones de la matriz y el segundo el valor que tendria

np.full([3,3],3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

## Acceso a los elementos de un array

In [19]:
# funcion que determina la dimension de mi array

a1.ndim

1

In [22]:
# funcion que me indica la forma de mi array

a2.shape

(2, 3)

In [23]:
# funcion que determina el numero de elementos

array3.size

9

In [24]:
#  funcion que indica el tipo de dato que tienes en tu array. 
# Int: numero entero, Float: numeros con decimales, str(string): texto, datatime: fechas

a1.dtype

dtype('int32')

In [25]:
a = np.array([[1,2,3],[4,5,6]])

In [29]:
#funcion que remodela la array, cambiandole de forma con los argumentos de: llamada al array, las formas. no se puede remodelar algo que no existe

np.reshape(a, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.reshape(a, (3,3)) #Error

In [30]:
# Acceder a los elementos de una array

print(a[1,0])

4


In [34]:
# Filtrado de arrays en base a una condicion matematica:

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[1, 1, 1], [2, 2, 2]])

print(c / d)# dividir


print(c**2)# exponente


print(c%d)# resto

print(c==d)# ¿son iguales?

[[1.  2.  3. ]
 [2.  2.5 3. ]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 1 0]]
[[ True False False]
 [False False False]]


In [35]:
# La funcion .dot nos devuelve el producto matricia, para poder hacer el producto matricial debe seguir la siguiente condicion, si a= m*n y b=n*p entonces AB = m*p
# AB sera las columnas de a y las filas de b 
# La funcion T da la matriz traspuesta

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])

print(a.dot(b))


[[14 14]
 [32 32]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Transponer un array con la funcion T. Convierte las filas de la matriz en columnas y las columnas en filas

print(a.T)

## Tema 2. Numpy Fechas

In [12]:
# Objetivo: acceder a los distintos componentes de una fecha
# Convertir cadenas de formato de fecha en los tipos date, time, datetime. De acuerdo a diferentes tipos de fecha (YYYY/MM/DD)
# Hacer aritmetica con fechas, comparativa de fechas para un analisis de tiempo.


from datetime import date, time, datetime, timedelta

In [39]:
date(1989,4,10)

datetime.date(1989, 4, 10)

In [40]:
# quiero lo mismo pero con tiempo: hora , minutosm, segundos y minisegundos

time(12,32,25,3)

datetime.time(12, 32, 25, 3)

In [41]:

print(datetime(2020,12,30,11,30,5,3))

2020-12-30 11:30:05.000003


In [52]:
d=date.today()

In [57]:
# ¿Que dia es hoy?


print("Hoy es:",d,"con hora:",datetime.now(),"con numero del dia de la semana", d.weekday())

Hoy es: 2023-05-03 con hora: 2023-05-03 20:44:55.212112 con numero del dia de la semana 2


In [56]:
# Poner solo la hora de ahora sin la fecha

print("Hoy es:",d,"con hora:",datetime.now().time(),"con numero del dia de la semana", d.weekday())

Hoy es: 2023-05-03 con hora: 20:44:52.120984 con numero del dia de la semana 2


In [58]:
#genera el año actual

d.year

2023

In [59]:
# genera el mes actual

d.month



5

In [60]:
# genera el dia 

d.day

3

In [68]:
t=datetime.now().time()

In [69]:
#la hora actual

t.hour

20

In [73]:
#el minuto exacto

t.minute

50

In [74]:
t.second

31

In [79]:
a = datetime.now()

In [89]:
#conversion de fechas en cadenas con diferentes formatos



fecha = print(a.strftime('%d/%B/%y %H-%M-%S'))

03/May/23 20-59-11


In [95]:
print(datetime.strptime('15/4/2020', '%d/%m/%Y'))

2020-04-15 00:00:00


In [23]:
# timedelta se usa para operaciones matematicas con las fechas. Dentro de los parentesis se pondra el valor en dias y segundos.
d1 = datetime(2020, 1, 1)
print(d1 + timedelta(31, 3600))

2020-02-01 01:00:00


In [20]:
# Restar datetime mas la fecha dada

datetime.now() - d1

datetime.timedelta(days=1219, seconds=67594, microseconds=280078)

In [24]:
# Cual es la fecha de tres meses y cuatro dias a partir de hoy??

dtoday = date.today()
print(timedelta(97) + dtoday) #97 son 31 dias de un mes por 4 mas 4 dias extra

2023-08-09


In [18]:
# Que dia empecamos con las clases de LyM? 

print(dtoday - timedelta(7))

2023-04-27


In [25]:
dtoday - d1


TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'