# Ejercicios Numpy 1

## 1. ¿Cuál es la forma de convertir una lista en Python a un array en Numpy?

In [6]:
#Para convertir una lista en Python a un array en NumPy, se utiliza la función numpy.array().

import numpy as np # importat numpy servira para todo el notebook

lista = [1, 2, 3, 4, 5]
array = np.array(lista)

print(array)

[1 2 3 4 5]


## 2. Para crear un array de ceros con una forma específica, ¿qué función se utiliza?

In [7]:
#Para crear un array de ceros con una forma específica en NumPy, se utiliza la función numpy.zeros()


forma = (3, 4)  # 3 filas, 4 columnas
array_zeros = np.zeros(forma)

print(array_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 3. ¿Qué función se emplea para crear un array multidimensional de unos con una forma específica?

In [8]:
#Para crear un array multidimensional de unos con una forma específica en NumPy, se utiliza la función numpy.ones().


forma = (2, 3)  
array_ones = np.ones(forma)

print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


## 4. ¿De qué manera se obtiene la suma de todos los elementos de un array?

In [9]:
#Para obtener la suma de todos los elementos de un array en NumPy, se puede utilizar la función numpy.sum().

array = np.array([1, 2, 3, 4, 5])
suma = np.sum(array)

print(suma)

15


## 5. ¿Cómo efectuar una multiplicación elemento a elemento de dos arrays?

In [10]:
# Para efectuar una multiplicación elemento a elemento de dos arrays en NumPy, se utiliza el operador * entre los dos arrays. 
# Los arrays deben tener la misma forma para que la multiplicación sea válida. 


array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

resultado = array1 * array2

print(resultado)

[ 4 10 18]


## 6. ¿Qué atributo se utiliza para obtener la forma de un array?


In [11]:
# Para obtener la forma de un array en NumPy, se utiliza el atributo shape.


array = np.array([[1, 2, 3], [4, 5, 6]])
forma = array.shape

print(forma)

(2, 3)


## 7. ¿Cuál es el proceso para redimensionar un array sin cambiar sus datos?


In [1]:
# Para redimensionar un array en NumPy sin cambiar sus datos, se utiliza el método reshape() en el array.


array = np.array([1, 2, 3, 4, 5, 6])
nuevo_array = array.reshape((2, 3))  # Nueva forma: 2 filas, 3 columnas

print(nuevo_array)


[[1 2 3]
 [4 5 6]]


## 8. ¿Qué función permite crear un array con un rango de números?


In [12]:
#Para crear un array con un rango de números en NumPy, se puede utilizar la función numpy.arange().


arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


## 9. Al querer generar un array con valores equiespaciados, ¿qué función se usa?


In [13]:
# Para generar un array con valores equiespaciados en NumPy, se puede utilizar la función numpy.linspace().


inicio = 0
fin = 1
num_elementos = 5

array_new = np.linspace(inicio, fin, num_elementos)

print(array_new)
# se generará un array con 5 elementos que van desde 0 hasta 1, ambos inclusive.

[0.   0.25 0.5  0.75 1.  ]


## 10.¿Cómo determinar el valor mínimo y máximo de un array?


In [14]:
# Para determinar el valor mínimo y máximo de un array en NumPy, se utilizan las funciones numpy.min() y numpy.max() respectivamente.


array = np.array([4, 2, 9, 7, 5])

valor_minimo = np.min(array)
valor_maximo = np.max(array)

print(valor_minimo)
print(valor_maximo)

2
9


## 11.En un array, ¿cómo se calculan la media, mediana y desviación estándar de sus elementos?


In [15]:
# En un array en NumPy, se pueden calcular la media, mediana y desviación estándar de sus elementos
# utilizando las funciones numpy.mean(), numpy.median() y numpy.std() 


array = np.array([1, 2, 3, 4, 5])

media = np.mean(array)
mediana = np.median(array)
desviacion_estandar = np.std(array)

print("Media:", media)
print("Mediana:", mediana)
print("Desviación estándar:", desviacion_estandar)

Media: 3.0
Mediana: 3.0
Desviación estándar: 1.4142135623730951


## 12.¿Cuál es el procedimiento para transponer un array 2D (intercambiar filas por columnas)?


In [16]:
# Para transponer un array 2D en NumPy, es decir, intercambiar filas por columnas, se puede utilizar el atributo T del array.


array = np.array([[1, 2, 3], [4, 5, 6]])

array_transpuesto = array.T

print(array_transpuesto)

# se transpone el array original de 2 filas y 3 columnas, resultando en un nuevo array de 3 filas y 2 columnas

[[1 4]
 [2 5]
 [3 6]]


## 13.¿De qué manera se calcula el producto punto (dot product) de dos arrays?

In [17]:
# Para calcular el producto punto (dot product) de dos arrays en NumPy, se utiliza la función numpy.dot().


array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

producto_punto = np.dot(array1, array2)


print(producto_punto)

# El resultado será el producto punto de los dos arrays, que en este caso es 32 (1*4 + 2*5 + 3*6).

32
