# Reto 2

## Manipulación y procesado de datos


In [2]:
import numpy as np

###  1. Crear una matriz numpy vacía de números enteros y otra completa

In [3]:
print(np.zeros((3,4)))
print(np.full([3,3],3))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


### 2. Crea un array y conviértelo en una matriz de 3 columnas y 5 filas

In [4]:
array = np.arange(1, 16)  
 
matriz = array.reshape(5, 3)

print(matriz)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


### 3. Todos los elementos de un array deben tener el mismo tipo de dato, crea un array booleano y comprueba el tipo de dato. Luego crea uno con tipos de datos distintos y comprueba el tipo de resultado.

In [6]:
bool = np.array([True, False, True, False])


print("Tipo de dato del array booleano:",bool.dtype)


dato = np.array([1, 2.5, "tres", True])


print("Tipo de dato del array mixto:",dato.dtype)

Tipo de dato del array booleano: bool
Tipo de dato del array mixto: <U32


### 4. Filtra el nombre Julio en los elementos del siguiente array: Julio, Jose, Alberto, Julio, Nuria, Daniel.

In [11]:
nombres = ["Julio", "Jose", "Alberto", "Julio", "Nuria", "Daniel"]

resultado = [nombre for nombre in nombres if nombre == "Julio"]

print(resultado)

['Julio', 'Julio']


### 5. Crea una un array de 20 elementos numéricos y encuentra la raíz cuadrada y exponencial

In [12]:
array = np.random.rand(20) 
raices_cuadradas = np.sqrt(array)
exponenciales = np.exp(array)

print("Array original:")
print(array)
print("Raíz cuadrada de cada elemento:")
print(raices_cuadradas)
print("Exponencial de cada elemento:")
print(exponenciales)

Array original:
[0.37231033 0.0554694  0.65814581 0.02157904 0.88460646 0.38144181
 0.15199391 0.43326246 0.43663439 0.41385241 0.9478986  0.02665208
 0.64091423 0.58100326 0.82388246 0.89714715 0.24883397 0.16948438
 0.43419675 0.14493309]
Raíz cuadrada de cada elemento:
[0.61017238 0.23551942 0.81126186 0.14689806 0.9405352  0.61760975
 0.38986397 0.65822675 0.66078317 0.64331362 0.97360084 0.16325464
 0.80057119 0.7622357  0.90767971 0.94717852 0.49883261 0.4116848
 0.65893607 0.38070079]
Exponencial de cada elemento:
[1.45108322 1.05703667 1.93120819 1.02181355 2.42203104 1.46439445
 1.16415315 1.54228095 1.5474902  1.51263386 2.58028175 1.02701042
 1.89821549 1.78783119 2.27933209 2.45259624 1.28252908 1.18469384
 1.54372257 1.15596222]


### 6. Matemáticas:

In [16]:
# 6.1 Crea un array de -5 a 6.

array5 = np.arange(-5, 7) 
print(array5)

[-5 -4 -3 -2 -1  0  1  2  3  4  5  6]


In [17]:
# 6.2 Multiplica por 2.5 todos los elementos del array.
m = array5 * 2.5
print(m)

[-12.5 -10.   -7.5  -5.   -2.5   0.    2.5   5.    7.5  10.   12.5  15. ]


In [21]:
# 6.3 Filtra los elementos del array que son mayores de -3 y menores de 5.


resultado = [elemento for elemento in m if -3 < elemento < 5]

print(resultado)

[-2.5, 0.0, 2.5]


In [23]:
# 6.4 Transforma el array para añadir 1 a todos los elementos negativos (Usa una función)

m = np.array([-12.5, -10.0, -7.5, -5.0, -2.5, 0.0, 2.5, 5.0, 7.5, 10.0, 12.5, 15.0])

resultado = np.add(m, np.where(m < 0, 1, 0))

print(resultado)

[-11.5  -9.   -6.5  -4.   -1.5   0.    2.5   5.    7.5  10.   12.5  15. ]


In [22]:
# 6.5 Imprime la suma del array
print(sum(m))


15.0
